######################################################################
# Automatically generated by qmake (2.01a) Tue May 6 11:03:29 2008
######################################################################

TEMPLATE = lib
TARGET = xlibevents
DEPENDPATH += .
INCLUDEPATH += . $(JAVA_HOME)/include $(JAVA_HOME)/include/linux /usr/include/X11 
LIBS += -lX11

# Input
HEADERS += os.h
SOURCES += os.cpp
