/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_swt_widgets_DCControl */

#ifndef _Included_org_eclipse_swt_widgets_DCControl
#define _Included_org_eclipse_swt_widgets_DCControl
#ifdef __cplusplus
extern "C"
{
#endif
#undef org_eclipse_swt_widgets_DCControl_DISPOSED
#define org_eclipse_swt_widgets_DCControl_DISPOSED 1L
#undef org_eclipse_swt_widgets_DCControl_CANVAS
#define org_eclipse_swt_widgets_DCControl_CANVAS 2L
#undef org_eclipse_swt_widgets_DCControl_KEYED_DATA
#define org_eclipse_swt_widgets_DCControl_KEYED_DATA 4L
#undef org_eclipse_swt_widgets_DCControl_DISABLED
#define org_eclipse_swt_widgets_DCControl_DISABLED 8L
#undef org_eclipse_swt_widgets_DCControl_HIDDEN
#define org_eclipse_swt_widgets_DCControl_HIDDEN 16L
#undef org_eclipse_swt_widgets_DCControl_GRAB
#define org_eclipse_swt_widgets_DCControl_GRAB 32L
#undef org_eclipse_swt_widgets_DCControl_MOVED
#define org_eclipse_swt_widgets_DCControl_MOVED 64L
#undef org_eclipse_swt_widgets_DCControl_RESIZED
#define org_eclipse_swt_widgets_DCControl_RESIZED 128L
#undef org_eclipse_swt_widgets_DCControl_EXPANDING
#define org_eclipse_swt_widgets_DCControl_EXPANDING 256L
#undef org_eclipse_swt_widgets_DCControl_LAYOUT_NEEDED
#define org_eclipse_swt_widgets_DCControl_LAYOUT_NEEDED 512L
#undef org_eclipse_swt_widgets_DCControl_LAYOUT_CHANGED
#define org_eclipse_swt_widgets_DCControl_LAYOUT_CHANGED 1024L
#undef org_eclipse_swt_widgets_DCControl_IGNORE_WHEEL
#define org_eclipse_swt_widgets_DCControl_IGNORE_WHEEL 2048L
#undef org_eclipse_swt_widgets_DCControl_DEFAULT_WIDTH
#define org_eclipse_swt_widgets_DCControl_DEFAULT_WIDTH 64L
#undef org_eclipse_swt_widgets_DCControl_DEFAULT_HEIGHT
#define org_eclipse_swt_widgets_DCControl_DEFAULT_HEIGHT 64L
    /*
     * Class:     org_eclipse_swt_widgets_DCControl
     * Method:    _createDCControl
     * Signature: (II)I
     */
    JNIEXPORT jint JNICALL Java_org_eclipse_swt_widgets_DCControl__1createDCControl
    (JNIEnv *, jobject, jint, jint);

    /*
     * Class:     org_eclipse_swt_widgets_DCControl
     * Method:    _getControlHandle
     * Signature: (I)I
     */
    JNIEXPORT jint JNICALL Java_org_eclipse_swt_widgets_DCControl__1getControlHandle
    (JNIEnv *, jobject, jint);

    /*
     * Class:     org_eclipse_swt_widgets_DCControl
     * Method:    _drawNow
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_org_eclipse_swt_widgets_DCControl__1drawNow
    (JNIEnv *, jobject, jint);

    /*
     * Class:     org_eclipse_swt_widgets_DCControl
     * Method:    _setFullScreen
     * Signature: (IZ)V
     */
    JNIEXPORT void JNICALL Java_org_eclipse_swt_widgets_DCControl__1setFullScreen
    (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
